colourful: true

filekinds:
  normal: {foreground: "#DCD7BA"}
  directory: {foreground: "#7E9CD8"}
  symlink: {foreground: "#6A9589"}
  pipe: {foreground: "#C0A36E"}
  block_device: {foreground: "#E6C384", is_bold: true}
  char_device: {foreground: "#E6C384", is_bold: true}
  socket: {foreground: "#957FB8"}
  special: {foreground: "#E6C384"}
  executable: {foreground: "#FF5D62", is_bold: true}
  mount_point: {foreground: "#7FB4CA", is_bold: true, is_underlined: true}

perms:
  user_read: {foreground: "#E6C384", is_bold: true}
  user_write: {foreground: "#FF5D62", is_bold: true}
  user_execute_file: {foreground: "#7AA89F", is_bold: true}
  user_execute_other: {foreground: "#6A9589", is_bold: true}
  group_read: {foreground: "#E6C384"}
  group_write: {foreground: "#FF5D62"}
  group_execute: {foreground: "#7AA89F"}
  other_read: {foreground: "#E6C384"}
  other_write: {foreground: "#FF5D62"}
  other_execute: {foreground: "#7AA89F"}
  special_user_file: {foreground: "#957FB8"}
  special_other: {foreground: "#957FB8"}
  attribute: {foreground: "#DCD7BA"}

size:
  major: {foreground: "#6A9598", is_bold: true}
  minor: {foreground: "#6A9598"}
  number_byte: {foreground: "#6A9598", is_bold: true}
  number_kilo: {foreground: "#6A9598", is_bold: true}
  number_mega: {foreground: "#6A9598", is_bold: true}
  number_giga: {foreground: "#6A9598", is_bold: true}
  number_huge: {foreground: "#6A9598", is_bold: true}
  unit_byte: {foreground: "#6A9598"}
  unit_kilo: {foreground: "#6A9598"}
  unit_mega: {foreground: "#6A9598"}
  unit_giga: {foreground: "#6A9598"}
  unit_huge: {foreground: "#6A9598"}

users:
  user_you: {foreground: "#C0A36E"}
  user_root: {foreground: "#DCD7BA"}
  user_other: {foreground: "#957FB8"}
  group_yours: {foreground: "#C0A36E"}
  group_other: {foreground: "#957FB8"}
  group_root: {foreground: "#DCD7BA"}

links:
  normal: {foreground: Red, is_bold: true}
  multi_link_file: {foreground: Red, background: Yellow}

git:
  new: {foreground: "#76946A"}
  modified: {foreground: "#DCA561"}
  deleted: {foreground: "#C34043"}
  renamed: {foreground: "#2D4F67"}
  typechange: {foreground: "#957FB8"}
  ignored: {foreground: "#727169", is_dimmed: true}
  conflicted: {foreground: "#E82424"}

git_repo:
  branch_main: {foreground: "#6A9598"}
  branch_other: {foreground: "#FF9E3B"}
  git_clean: {foreground: "#6A9598"}
  git_dirty: {foreground: "#FF9E3B"}

security_context:
  colon: {foreground: Default, is_dimmed: true}
  user: {foreground: Blue}
  role: {foreground: Green}
  typ: {foreground: Yellow}
  range: {foreground: Cyan}

file_type:
  image: {foreground: Purple}
  video: {foreground: Purple, is_bold: true}
  music: {foreground: Cyan}
  lossless: {foreground: Cyan, is_bold: true}
  crypto: {foreground: Green, is_bold: true}
  document: {foreground: Green}
  compressed: {foreground: Red}
  temp: {foreground: White}
  compiled: {foreground: Yellow}
  build: {foreground: Yellow, is_bold: true, is_underlined: true}
  source: {foreground: Yellow, is_bold: true}

punctuation: {foreground: "#54546D", is_bold: true}
date: {foreground: "#C8C093"}
inode: {foreground: Purple}
blocks: {foreground: Cyan}
header: {foreground: Default, is_underlined: true}
octal: {foreground: Purple}
flags: {foreground: Default}

symlink_path: {foreground: Cyan}
control_char: {foreground: Red}
broken_symlink: {foreground: "#E82424"}
broken_path_overlay: {foreground: Default, is_underlined: true}
