CompileFlags:
  Add: [-Wall, -Wextra]

Completion:
  ArgumentLists: Delimiters

Hover:
  ShowAKA: true

Diagnostics:
  Suppress: [unused-parameter]

---
If:
  PathMatch: .*\.(cpp|hpp)$
CompileFlags:
  Add: [-std=c++23,-Wno-c23-extensions]

---
If:
  PathMatch: .*\.(c|h)
CompileFlags:
  Add: [-std=c17]
