CompileFlags:
  Add: [-Wall, -Wextra]

Completion:
  ArgumentLists: Delimiters

Hover:
  ShowAKA: true

---
If:
  PathMatch: .*\.(cpp|hpp|h)$
CompileFlags:
  Add: [-std=c++20]

---
If:
  PathMatch: .*\.c
CompileFlags:
  Add: [-std=c17]
