CompileFlags:
  Add: [-Wall, -Wextra]

Completion:
  ArgumentLists: Delimiters

Hover:
  ShowAKA: true

Diagnostics:
  Suppress: [ unused-parameter ]

---
If:
  PathMatch: .*\.(cpp|hpp|h)$
CompileFlags:
  Add: [-std=c++23]

---
If:
  PathMatch: .*\.c
CompileFlags:
  Add: [-std=c17]
