#!/bin/bash

# colors
RED='\x1b[38;2;232;36;36m' # #e82424

# check there is at least one directory in ~/.mozilla/firefox
exists_profile=false
for item in ~/.mozilla/firefox/*; do
  if [[ -d "$item" ]]; then
    exists_profile=true
    break
  fi
done
$exists_profile || {
  echo -e "${RED}Where even is your Zen profile ?"
  exit 1
}

# let the user select a profile through fzf
ZENPROFILE=$(fd --hidden --max-depth 1 -td . ~/.mozilla/firefox | fzf --select-1 --preview='eza -1alh --group-directories-first --color=always --icons {}')
while [[ -z "$ZENPROFILE" ]]; do
  ZENPROFILE=$(fd --hidden --max-depth 1 -td . ~/.mozilla/firefox | fzf --select-1 --preview='eza -1alh --group-directories-first --color=always --icons {}')
done

# create symbolic links
for item in ~/.config/browser/profile/*; do
  stripped="${item%/}" # strip trailing slash (if any)
  name="${stripped##*/}"

  [[ -e "$ZENPROFILE/$name" || -L "$ZENPROFILE/$name" ]] && rm -rf "${ZENPROFILE:?}/$name"
  ln -s "$item" "$ZENPROFILE/$name"
done
