user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.anchor_color", "#7e9cd8");
user_pref("browser.display.background_color", "#dcd7ba");
user_pref("browser.display.foreground_color", "#16161d");
user_pref("browser.download.dir", "/home/Antoine/Téléchargements");
user_pref("browser.startup.homepage", "file:///home/Antoine/.config/browser/browser-homepage.html");
user_pref("devtools.debugger.remote-enabled", true);
user_pref("layout.css.devPixelsPerPx", "1.35");
user_pref("mod.cleanedurlbar.customcolor", "hsl(0 0 10)");
user_pref("mod.cleanedurlbar.customselectcolor", "rgba(80, 80, 250, 0.75)");
user_pref("mod.cleanedurlbar.customselectfontcolor", "rgba(255,255,255,1)");
user_pref("mod.cleanedurlbar.customtransparency", "40%");
user_pref("theme.sidebar_expand_on_hover.collapse_buttons", true);
user_pref("theme.sidebar_expand_on_hover.custom_background", true);
user_pref("theme.sidebar_expand_on_hover.default_tab_background_shape", true);
user_pref("theme.sidebar_expand_on_hover.expanded_width", "500px");
user_pref("theme.sidebar_expand_on_hover.inverted_tabs", false);
user_pref("theme.sidebar_expand_on_hover.transition_speed", "120ms");
user_pref("uc.tabs.custom_color_hex", "#DCD7BA");
user_pref("uc.tabtextsize.textsize", "16");
user_pref("zen.theme.accent-color", "#7E9CD8");
user_pref("zen.urlbar.behavior", "float");
