[[manager.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[manager.prepend_keymap]]
on   = "2"
run  = "plugin smart-switch --args=1"
desc = "Switch or create tab 2"

[[manager.prepend_keymap]]
on  = "J"
run = "arrow 5"

[[manager.prepend_keymap]]
on  = "K"
run = "arrow -5"

[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on  = "<C-m>"
run = 'shell --block -- neomutt -a "$@"'

[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
