wrap = false       # wether to wrap long lines or not
wraplen = 120      # max column limit
tabsize = 1        # number of characters to use for indentation
tabchar = "tab"    # use tabs instead of spaces
verbosity = "warn" # show warnings
