###################################################################################
# This is oly's configuration file.                                               #
# Please edit the following values.                                               #
#                                                                                 #
# A list of all possible configuration options and their defaults can be found at #
# https://github.com/anonymousgrasshopper/oly/blob/main/src/config.cpp#L77-#L137  #
###################################################################################

# The author's name in the preview and generated pdf
author: Antoine Saez Dumas

# The base path where solutions are stored
base_path: ~/Mathématiques/Solutions

# the markup language the solutions are typed in
# must be one of latex or typst (default latex)
markup: typst

# you can set a different language to use with
# the tex and typst preamble files
language: french

# The pdf viewer used for 'oly gen'
pdf_viewer: zathura

# wether to confirm deletion or not in 'oly rm'
confirm: true

# map contest names to other ones
abbreviations:
  Shortlist: ISL

# added right after \documentclass in the preview file
packages: '\usepackage[french]{antoine}

\usepackage[sexy,diagrams]{evan}'
