#!/usr/bin/env zsh

# removes corrupted lines from the zsh history file

[[ -f "$HISTFILE" ]] || exit
cd "$(dirname "$HISTFILE")"
mv "$HISTFILE" corrupt_zsh_history
strings corrupt_zsh_history >"$HISTFILE"
fc -R "$HISTFILE"
rm corrupt_zsh_history
