#!/bin/bash

if [[ -d $1 ]]; then
  eza -1alh --git --group-directories-first --color=always --icons "$1"
elif [[ -f $1 ]]; then
  filetype=$(file --brief "$1")
  if echo "$filetype" | grep --silent "image"; then
    kitten icat "$1" 2>/dev/null
  elif [[ "$1" = *.md ]]; then
    glow -s dark "$1"
  elif echo "$filetype" | grep --silent "ASCII text"; then
    bat --number --color=always "$1"
  else
    hexyl "$1"
  fi
elif [[ -n $(printenv "$1") ]]; then
  if [[ "$1" == PATH ]]; then
    echo -e "${PATH//:/\\n}"
  else
    printenv "$1"
  fi
else
  true
fi
