#!/bin/bash

RED='\033[0;31m'

# list of configs and scripts to copy
configs=("bat" "btop" "clang-format" "eza" "fastfetch" "git" "i3" "kitty" "lazygit" "ncdu" "npm" "nvim" "rofi" "stylua.toml" "tmux" "wallpapers" "wget" "yazi" "zathura" "zsh" "fzf.conf" "ripgrep.conf" "shellcheckrc")
scripts=("codelldb_stdio_redirection" "compile_sfml" "fzf_preview_wrapper" "git_dotfiles" "remove_codelldb_stdio_redirection")

# clone the repo if it is not in ~/.config ans cd into it
[[ -d ~/.config ]] || mkdir ~/.config
cd ~/.config
[[ -d ~/.config/dotfiles ]] || git clone https://github.com/anonymousgrasshopper/dotfiles
cd ~/.config/dotfiles

# overwrite configs in the dotfiles repo
for config in ${configs[@]}; do
  if [[ -d "config/$config" || -f "config/$config" ]]; then
    rm -rf "config/$config"
  fi
  if [[ -d "$HOME/.config/$config" || -f "$HOME/.config/$config" ]]; then
    cp -r "$HOME/.config/$config" "config"
  else
    echo "${RED}/usr/local/bin/$script not found."
  fi
done
# overwrite scripts in the dotfiles repo
for script in ${scripts[@]}; do
  if [[ -f "scripts/$script" ]]; then
    rm -rf "scripts/$script"
  fi
  if [[ -f "/usr/local/bin/$script" ]]; then
    cp "/usr/local/bin/$script" "scripts"
  else
    echo "${RED}/usr/local/bin/$script not found."
  fi
done

# remove zcompdump
[[ -f "config/zsh/.zcompdump" ]] && rm "config/zsh/.zcompdump"

# remove tmux plugins directory
[[ -d "config/tmux/plugins" ]] && rm -rf "config/tmux/plugins"

# git add
sudo git add .

# commit if args are passed to the scripts
if [[ $# == 2 ]]; then
  sudo -E git commit -m"$1" -m"$2"
  git push
elif [[ $# == 1 ]]; then
  sudo -E git commit -m"$1"
  git push
fi
