#!/bin/bash

# list of configs to copy
configs=("bat" "btop" "eza" "git" "i3" "kitty" "lazygit" "ncdu" "npm" "nvim" "rofi" "tmux" "wallpapers" "wget" "yazi" "zathura" "zsh" "archey3.cfg" "fzf.conf" "ripgrep.conf" "shellcheckrc")

# clone the repo if it is not in ~/.config
[[ -d ~/.config/dotfiles ]] || git clone https://github.com/anonymousgrasshopper/dotfiles:~/.config

cd "$HOME/.config/dotfiles"

# overwrite configs in the dotfiles repo
for config in ${configs[@]}; do
  if [[ -d "config/$config" || -f "config/$config" ]]; then
    rm -rf "config/$config"
    if [[ -d "$HOME/.config/$config" || -f "$HOME/.config/$config" ]]; then
      cp -r "$HOME/.config/$config" "config"
    fi
  fi
done

# remove zcompdump
[[ ! -f "config/zsh/.zcompdump" ]] || rm "config/zsh/.zcompdump"

# git add
sudo git add ~/.config/dotfiles

# commit if args are passed to the scripts
if [[ $# == 2 ]]; then
  sudo -E git commit -m"$1" -m"$2"
  git push
elif [[ $# == 1 ]]; then
  sudo -E git commit -m"$1"
  git push
fi
