[manager]
cwd = { fg = "#e6c384" }
hovered = { reversed = true }
preview_hovered = { }

find_keyword = { fg = "#DCA561", bg = "#1f1f28" }
find_position = {}

tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

marker_copied = { fg = "#98bb6c" }
marker_cut = { fg = "#e46876" }
marker_selected = { fg = "#ffa066" }
marker_marked = { fg = "#957fb8" }

count_copied = { fg = "#1f1f28", bg = "#98bb6c" }
count_cut = { fg = "#1f1f28", bg = "#e46876" }
count_selected = { fg = "#1f1f28", bg = "#ffa066" }

border_symbol = "│"
border_style = { fg = "#54546D" }


[mode]
normal_main = { fg = "#1f1f28", bg = "#7E9CD8" }
normal_alt = { fg = "#9CABCA", bg = "#54546D" }
select_main = { fg = "#1f1f28", bg = "#957fb8" }
select_alt = { fg = "#9CABCA", bg = "#54546D" }
unset_main = { fg = "#1f1f28", bg = "#DCA561" }
unset_alt = { fg = "#9CABCA", bg = "#54546D" }


[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "reset", bg = "#2a2a37" }

progress_label = { fg = "#7e9cd8", bg = "#2a2a37", bold = true }
progress_normal = { fg = "#2a2a37", bg = "#1f1f28" }
progress_error = { fg = "#2a2a37", bg = "#1f1f28" }

perm_type = { fg = "#98bb6c" }
perm_read = { fg = "#e6c384" }
perm_write = { fg = "#ff5d62" }
perm_exec = { fg = "#7aa89f" }
perm_sep = { fg = "#957fb8" }


[pick]
border = { fg = "#54546D" }
active = { fg = "#957fb8", bold = true }
inactive = {}

[input]
border = { fg = "#54546D" }
title = { fg = "#DCD7BA" }
value = {}
selected = { reversed = true }

[completion]
border = { fg = "#54546D" }
active = { reversed = true }
inactive = {}

[tasks]
border = { fg = "#54546D" }
title = {}
hovered = { fg = "#957fb8" }

[which]
cols = 2
separator = " - "
separator_style = { fg = "#727169" }
mask = { bg = "#16161d" }
rest = { fg = "#727169" }
cand = { fg = "#7e9cd8" }
desc = { fg = "#54546d" }

[help]
on = { fg = "#7aa89f" }
run = { fg = "#957fb8" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#1f1f28", bg = "#dcd7ba" }

[notify]
title_info = { fg = "#6A9598" }
title_warn = { fg = "#FF9E3B" }
title_error = { fg = "#E82424" }

# files
[filetype]
rules = [
    { mime = "image/*", fg = "#e6c384" },
    { mime = "{audio,video}/*", fg = "#957fb8" },
    { mime = "application/{,g}zip", fg = "#e46876" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e46876" },
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#6a9589" },
    { name = "*", is = "orphan", fg = "#e46876" },
    { name = "*", is = "exec", fg = "#957fb8" },
    { name = "*/", fg = "#7e9cd8" },
]
