[manager]
ratio = [1,2,2]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
sort_translit = true
show_hidden = true
show_symlink = true
scrollof = 200

[preview]
wrap = "no"
tab_size = 2
cache_dir = "/home/Antoine/.cache/yazi"
image_filter = "nearest"

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
]
